import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import StoreProvider from "@/redux/store/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Meeting Sitation",
  description: "Generated by create next app",
};

// Assuming LayoutProps is defined somewhere in your Next.js types
type RootLayoutProps = {
  children: React.ReactNode;
  params: Promise<{
    locale: string; // Now defined as a promise that resolves to an object
  }>;
};

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const { locale } = await params; // Await the promise to get the locale

  return (
    <StoreProvider>
      <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
        <body className={inter.className}>
          {children}
          <Toaster position="top-center" richColors />
        </body>
      </html>
    </StoreProvider>
  );
}
